In [1]:
import torch

In [2]:
#Tensor
a = torch.Tensor([[1,2],[3,4],[5,6]])
print("A is {}".format(a))
b = torch.LongTensor([[1,2],[3,4],[5,6]])
print("B is {}".format(b))
c = torch.zeros((3,2))
print("C is {}".format(c))
d = torch.randn((3,2))
print("D is {}".format(d))
#Tensor和ndarray可以互相转换

A is tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
B is tensor([[1, 2],
        [3, 4],
        [5, 6]])
C is tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
D is tensor([[-2.0380,  1.5197],
        [ 0.2207, -0.0692],
        [-0.1221,  0.5043]])


In [3]:
#Variable
x = torch.autograd.Variable(torch.Tensor([1]), requires_grad=True)
w1 = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
b1 = torch.autograd.Variable(torch.Tensor([3]), requires_grad=True)
w2 = torch.autograd.Variable(torch.Tensor([4]), requires_grad=True)
b2 = torch.autograd.Variable(torch.Tensor([5]), requires_grad=True)

mid = w1 * x + b1     #mid = 2x + 3
y = w2 * mid + b2     #y = 4mid + 5

y.backward()

print(x.grad,w1.grad,b1.grad)

tensor([8.]) tensor([4.]) tensor([4.])


In [4]:
x = torch.randn(3)
x = torch.autograd.Variable(x, requires_grad=True)

y = 2 * x
print(y)

y.backward(torch.FloatTensor([1,0.1,0.01]))
print(x.grad)

tensor([-1.7746, -3.2499, -1.7162], grad_fn=<MulBackward0>)
tensor([2.0000, 0.2000, 0.0200])
